# -*- coding: utf-8 -*-
"""LinearRegressionPenjualanMobil.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IDCfb_F94fEYYbLxZG4YdGyEo5pje6OJ
"""

# Mempersiapkan library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

# Memanggil Dataset
dataset = pd.read_excel('Penjualan Mobil.xlsx')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 1].values

dataset.keys()

dataset.shape

# Menampilkan isi sebagian dataset
dataku = pd.DataFrame(dataset)
dataku.head()

# Split Dataset menjadi Training Set dan Testing Set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test, = train_test_split(x, y, test_size = 0.2, random_state=0)

# Melakukan Fitting Simple Linear Regression pada Training Set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

# Memprediksi hasil Test Set
y_pred = regressor.predict(x_test)

# Visualisasi Data
plt.scatter(dataku.X, dataku.Y)
plt.xlabel("Usia Mobil")
plt.ylabel("Harga Mobil")
plt.title("Grafik Usia Mobil vs Harga Mobil")
plt.show

# Visualisasi Nilai Prediksi pada Training Set
# Ukuran plot
plt.figure(figsize=(10,8))

# Biru adalah data observasi
plt.scatter(x_train, y_train, color = 'blue')

# Garis merah adalah hasil prediksi dari machine learning
plt.plot(x_train, regressor.predict(x_train), color = 'red')

# Memberi Judul dan Label
plt.title('Usia Mobil terhadap Harga Mobil (Training Set)')
plt.xlabel('Usia Mobil')
plt.ylabel('Harga Mobil')

# Menampilkan plot
plt.show()

# Visualisasi Nilai Prediksi pada Test Set
# Ukuran plot
plt.figure(figsize=(10,8))

# Biru adalah data observasi
plt.scatter(x_test, y_test, color = 'blue')

# Garis merah adalah hasil prediksi dari machine learning
plt.plot(x_test, regressor.predict(x_test), color = 'red')

# Memberi Judul dan Label
plt.title('Usia Mobil terhadap Harga Mobil (Test Set)')
plt.xlabel('Usia Mobil')
plt.ylabel('Harga Mobil')

# Menampilkan plot
plt.show()