# -*- coding: utf-8 -*-
"""LinearRegresi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ChP7v5tJPKWEz9v2ucIU_WTuysxhRAl1
"""

#Import Library uang diperlukan Scipy
from scipy import stats

# x = data usia mobil (tahun)
x = [5, 4, 6, 5, 5, 5, 6, 6, 2, 7, 7]

# y = data harga mobil ($100)
y = [85, 103, 70, 82, 89, 98, 66, 95, 169, 70, 48]

slope, intercept, r, p, std_err = stats.linregress(x,y)

# Buat Fungsi Linear Regresi =>
def myfunc(x):
  return slope * x + intercept

harga_mobil = myfunc(4)

print(harga_mobil)